### PR TITLE
Fixed the Restaurant menu broken api

### PR DESCRIPTION
**Pull request by Aneeshh18**
Now the items are loading when user clicks for a restaurant. As the body wasn't loading for me due to CORS So i used path to access -/restaurant/229 and fixed it

### CODE REVIEW

**Comment by chinmay021** [comment]
Thanks for contributng @Aneeshh18 .
The functionality is working but few things are not working like - button doesn't remove items from cart also the CSS needs to be fixed.  these are the screenshot from earlier build, how it used to look. If you want you can try to fix the UI and also the button functionality. Also there is cart shown on the right whenever you add items. Try to fix those and ping me if you need any help 👍
Screenshot_20230221_023557
Screenshot_20230221_023624

**Comment by chinmay021** [comment]
@Aneeshh18 if you feel like that's a lot of work you can leave it. I'll merge you PR then work upon it once I start working on this again.

**Comment by Aneeshh18** [comment]
> @Aneeshh18 if you feel like that's a lot of work you can leave it. I'll merge you PR then work upon it once I start working on this again.

No problem I will fix that too!

**Comment by Aneeshh18** [comment]
@chinmay021 You didn't merge the PR, You still need some more changes?

**Comment by chinmay021** [comment]
@Aneeshh18 I was busy with my other project I'll merge this once I start working on this project again. Thanks for the help 👍

**Pull request closed without merging**
